### ISSUE TITLE
Exception when testing GMF diagram with windowtester

### ISSUE THREAD

**Issue by Tcharl** [fredg02/windowtester#1]
Hi,

I've got the following trace when testing GMF. Any workaround for the workaround?
Regards,

java.lang.NoSuchFieldException: menus
    at java.lang.Class.getDeclaredField(Class.java:1948)
    at com.windowtester.runtime.swt.internal.abbot.SWTWorkarounds.getMenus(SWTWorkarounds.java:469)
    at abbot.finder.swt.SWTHierarchy.addOrphanedMenus(SWTHierarchy.java:560)
    at abbot.finder.swt.SWTHierarchy.access$1(SWTHierarchy.java:558)
    at abbot.finder.swt.SWTHierarchy$WidgetGetter.getWidgets(SWTHierarchy.java:226)
    at abbot.finder.swt.SWTHierarchy$WidgetGetter.run(SWTHierarchy.java:181)
    at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
    at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
    at org.eclipse.swt.widgets.Display.syncExec(Display.java:4650)
    at abbot.finder.swt.SWTHierarchy.getWidgets(SWTHierarchy.java:316)
    at com.windowtester.runtime.swt.internal.finder.legacy.WidgetFinder$SingleWidgetHierarchy.getWidgets(WidgetFinder.java:93)
    at com.windowtester.runtime.swt.internal.finder.legacy.WidgetFinder.findMatches(WidgetFinder.java:344)
    at com.windowtester.runtime.swt.internal.finder.legacy.WidgetFinder$1.run(WidgetFinder.java:295)
    at com.windowtester.runtime.swt.internal.display.DisplayExec$1.call(DisplayExec.java:41)
    at com.windowtester.runtime.swt.internal.widgets.DisplayReference$5.call(DisplayReference.java:149)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.execute(SWTUIExecutor.java:142)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.run(SWTUIExecutor.java:97)
    at

**Comment by fredg02** [comment]
Please provide more details about the environment (Eclipse version, WindowTester version) and how this error can be reproduce.

**Comment by Tcharl** [comment]
Hi,

I'm on OSx with Eclipse Kepler on WindowTester Beta (tried with the patched version mentionned in the previous threads too). 
In order to reproduce, just create an EMF MM with an object that have not a 'name' property, then a GMF diagram on it with a tool that create this element.
When trying WT with testing this diagram, the error appears.
I'll try to make a sample proving this behaviour on a non enterprise project but when I'll have the time to make it...

**Comment by fredg02** [comment]
Hi,
your stacktrace points to a code segment that should not be reached on Mac OSX, so that's quite strange.
I have only limited access to a Mac OSX environment, so hopefully you can help me diagnose this behavior:
- In your Eclipse Kepler environment please create a new Eclipse plug-in project and add "org.eclipse.swt" as a required plug-in (MANIFEST.MF -> Dependencies Tab).
- Then create a new class in this plug-in with the following code:

```
import org.eclipse.swt.SWT;

    public class PlatformTest {

    public static final String OS_NAME;

    static {
        OS_NAME = System.getProperty("os.name");
    }

    private static boolean isMac = System.getProperty("mrj.version") != null;
    private static boolean isOSX = isMac && OS_NAME.indexOf("OS X") != -1;

    public static boolean isMacintosh() { return isMac; }
    public static boolean isMacCocoa() { return isMac && SWT.getPlatform().equals("cocoa"); }
    public static boolean isOSX() { return isOSX; }

    /**
     * @param args
     */
    public static void main(String[] args) {
        System.out.println("isMacintosh: " + isMacintosh());
        System.out.println("isMacCocoa: " + isMacCocoa());
        System.out.println("isOSX: " + isOSX());
        System.out.println("SWT.getPlatform(): " + SWT.getPlatform());
        System.out.println("SWT.getVersion(): " + SWT.getVersion());
        System.out.println("mrj.version: " + System.getProperty("mrj.version"));
        System.out.println("os.name: " + System.getProperty("os.name"));
        System.out.println("java.version: " + System.getProperty("java.version"));
    }
}

```
- Run the class as Java application and report back the output.

Thanks

**Comment by Tcharl** [comment]
Hi,

Here is the output:

isMacintosh: false
isMacCocoa: false
isOSX: false
SWT.getPlatform(): cocoa
SWT.getVersion(): 4333
mrj.version: null
os.name: Mac OS X
java.version: 1.7.0_45

**Comment by fredg02** [comment]
Hi,
So I guess the mrj.version returning null is the problem.
Which exact version of Mac OS X are you using?

Regards

**Comment by Tcharl** [comment]
Hi,
10.9.1 (Mavericks)

Can I help in other kind?

Regards

2013/12/24 Fred G notifications@github.com

> Hi,
> So I guess the mrj.version returning null is the problem.
> Which exact version of Mac OS X are you using?
> 
> Regards
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fredg02/windowtester/issues/1#issuecomment-31172028
> .

## 

Cordialement,

Charlie Mordant

**Comment by fredg02** [comment]
I'll try to provide a fix in the next days.
Maybe you can test it and provide feedback.

**Comment by Tcharl** [comment]
For sure!

Best regards,

2013/12/27 Fred G notifications@github.com

> I'll try to provide a fix in the next days.
> Maybe you can test it and provide feedback.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fredg02/windowtester/issues/1#issuecomment-31260960
> .

## 

Cordialement,

Charlie Mordant

**Comment by fredg02** [comment]
Hi,
Please download the zip file from https://buildhive.cloudbees.com/view/My%20Repositories/job/fredg02/job/windowtester/ws/com.windowtester_repository/target/com.windowtester.repository-6.1.0.201312291728.zip
and use it as local P2 update repository to install.
Let me know if it works.

Regards

**Comment by Tcharl** [comment]
Hi,

An error while opening a wizard:

ENTRY org.eclipse.ui 4 0 2013-12-30 00:49:23.675

!MESSAGE Unhandled event loop exception

!STACK 0

org.eclipse.swt.SWTException: Failed to execute runnable (
java.lang.UnsupportedOperationException: bounds should be provided by
OSX-specific plugins)

at org.eclipse.swt.SWT.error(SWT.java:4397)

at org.eclipse.swt.SWT.error(SWT.java:4312)

at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(
Synchronizer.java:138)

at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3976)

at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3653)

at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)

at org.eclipse.jface.window.Window.open(Window.java:802)

at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(
WizardShortcutAction.java:98)

at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)

at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(
ActionContributionItem.java:584)

at org.eclipse.jface.action.ActionContributionItem.access$2(
ActionContributionItem.java:501)

at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(
ActionContributionItem.java:411)

at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4166)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)

at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1474)

at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)

at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4012)

at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3651)

at
com.windowtester.runtime.swt.internal.junit.SWTExecutionMonitor.doWaitForFinish(
SWTExecutionMonitor.java:161)

at
com.windowtester.internal.runtime.junit.core.AbstractExecutionMonitor.waitUntilFinished(
AbstractExecutionMonitor.java:215)

at
com.windowtester.internal.runtime.junit.core.SequenceRunner.waitUntilFinished(
SequenceRunner.java:79)

at com.windowtester.internal.runtime.junit.core.SequenceRunner.exec(
SequenceRunner.java:63)

at com.windowtester.runtime.common.UITestCaseCommon.runUITest(
UITestCaseCommon.java:157)

at com.windowtester.runtime.common.UITestCaseCommon.runBare(
UITestCaseCommon.java:138)

at junit.framework.TestResult$1.protect(TestResult.java:122)

at junit.framework.TestResult.runProtected(TestResult.java:142)

at junit.framework.TestResult.run(TestResult.java:125)

at junit.framework.TestCase.run(TestCase.java:129)

at junit.framework.TestSuite.runTest(TestSuite.java:255)

at junit.framework.TestSuite.run(TestSuite.java:250)

at org.junit.internal.runners.JUnit38ClassRunner.run(
JUnit38ClassRunner.java:84)

at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(
JUnit4TestReference.java:50)

at org.eclipse.jdt.internal.junit.runner.TestExecution.run(
TestExecution.java:38)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(
RemoteTestRunner.java:467)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(
RemoteTestRunner.java:683)

at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(
RemoteTestRunner.java:390)

at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(
RemotePluginTestRunner.java:62)

at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness$1.run(
PlatformUITestHarness.java:47)

at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)

at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(
Synchronizer.java:135)

at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3976)

at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3653)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(
PartRenderingEngine.java:1113)

at org.eclipse.core.databinding.observable.Realm.runWithDefault(
Realm.java:332)

at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(
PartRenderingEngine.java:997)

at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(
E4Workbench.java:138)

at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)

at org.eclipse.core.databinding.observable.Realm.runWithDefault(
Realm.java:332)

at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(
Workbench.java:567)

at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)

at org.eclipse.ui.internal.ide.application.IDEApplication.start(
IDEApplication.java:124)

at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(
NonUIThreadTestApplication.java:54)

at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(
UITestApplication.java:47)

at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(
NonUIThreadTestApplication.java:48)

at org.eclipse.equinox.internal.app.EclipseAppHandle.run(
EclipseAppHandle.java:196)

at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(
EclipseAppLauncher.java:110)

at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(
EclipseAppLauncher.java:79)

at org.eclipse.core.runtime.adaptor.EclipseStarter.run(
EclipseStarter.java:354)

at org.eclipse.core.runtime.adaptor.EclipseStarter.run(
EclipseStarter.java:181)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(
NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(
DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:606)

at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)

at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)

at org.eclipse.equinox.launcher.Main.run(Main.java:1450)

at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

Caused by: java.lang.UnsupportedOperationException: bounds should be
provided by OSX-specific plugins

at com.windowtester.runtime.swt.internal.abbot.SWTWorkarounds.getBounds(
SWTWorkarounds.java:89)

at abbot.tester.swt.WidgetLocator.getBounds(WidgetLocator.java:145)

at abbot.tester.swt.WidgetLocator.getLocation(WidgetLocator.java:64)

at abbot.tester.swt.WidgetLocator.getLocation(WidgetLocator.java:46)

at com.windowtester.runtime.swt.internal.selector.UIDriver$5.run(
UIDriver.java:812)

at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)

at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(
Synchronizer.java:135)

... 66 more

Hope this helps,

Regards

2013/12/29 Fred G notifications@github.com

> Hi,
> Please download the zip file from
> https://buildhive.cloudbees.com/view/My%20Repositories/job/fredg02/job/windowtester/ws/com.windowtester_repository/target/com.windowtester.repository-6.1.0.201312291728.zip
> and use it as local P2 update repository to install.
> Let me know if it works.
> 
> Regards
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fredg02/windowtester/issues/1#issuecomment-31321191
> .

## 

Cordialement,

Charlie Mordant

**Comment by fredg02** [comment]
Thanks,
I'll have to wait until I have access to a Mac OS X system for further debugging and testing (probably some time next week).

**Comment by fredg02** [comment]
I can reproduce your "java.lang.UnsupportedOperationException: bounds should be provided by OSX-specific plugins" error now.
I'll try to fix it, but this might take a while.
Any chance you could provide a patch?

**Comment by Tcharl** [comment]
Hi,

Unfortunately not, I'm working on too many OSS projects for the moment...
Can I fill a bug somewhere to keep the information?

Regards and thank you for all.

Charlie

2014-01-30 Fred G notifications@github.com

> I can reproduce your "java.lang.UnsupportedOperationException: bounds
> should be provided by OSX-specific plugins" error now.
> I'll try to fix it, but this might take a while.
> Any chance you could provide a patch?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/fredg02/windowtester/issues/1#issuecomment-33711952
> .

## 

Cordialement,

Charlie Mordant

**Comment by fredg02** [comment]
Same here. ;)
You can also file a bug at https://code.google.com/p/windowtester/issues but I doubt that it's get more attention there.
