### ISSUE TITLE
WTRuntimeManager.createReference error

### ISSUE THREAD

**Issue by wendelkenEPA** [fredg02/windowtester#3]
Hey Fred, I've been trying to get this working the last few days but am currently running into an error:

`Quit waiting for UI thread to execute callable 1463751070952
Elapse time: 10007
Max wait time: 10000
UI Thread: Thread[Thread-0,5,main]
This Thread: Thread[WT Test Thread,5,main]
Thread[Reference Handler,10,system]:
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Unknown Source)
    at java.lang.ref.Reference.tryHandlePending(Unknown Source)
    at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
Thread[ReaderThread,5,main]:
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at java.io.BufferedReader.fill(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner$ReaderThread.run(RemoteTestRunner.java:135)
Thread[Finalizer,8,system]:
    at java.lang.Object.wait(Native Method)
    at java.lang.ref.ReferenceQueue.remove(Unknown Source)
    at java.lang.ref.ReferenceQueue.remove(Unknown Source)
    at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
Thread[WT Test Thread,5,main]:
    at java.lang.Thread.dumpThreads(Native Method)
    at java.lang.Thread.getAllStackTraces(Unknown Source)
    at com.windowtester.internal.debug.ThreadUtil.printStackTraces(ThreadUtil.java:86)
    at com.windowtester.internal.debug.ThreadUtil.printStackTraces(ThreadUtil.java:77)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.run(SWTUIExecutor.java:122)
    at com.windowtester.runtime.swt.internal.widgets.DisplayReference.execute(DisplayReference.java:131)
    at com.windowtester.runtime.swt.internal.widgets.DisplayReference.execute(DisplayReference.java:110)
    at com.windowtester.runtime.swt.internal.widgets.finder.SWTWidgetFinder.doFindAll(SWTWidgetFinder.java:116)
    at com.windowtester.runtime.swt.internal.widgets.finder.SWTWidgetFinder.findAll(SWTWidgetFinder.java:110)
    at com.windowtester.runtime.swt.condition.shell.ShellShowingCondition.test(ShellShowingCondition.java:57)
    at com.windowtester.internal.runtime.condition.ConditionMonitor.test(ConditionMonitor.java:186)
    at com.windowtester.runtime.swt.internal.UIContextSWT.wait(UIContextSWT.java:818)
    at com.windowtester.runtime.swt.internal.UIContextSWT.wait(UIContextSWT.java:804)
    at com.windowtester.runtime.swt.internal.UIContextSWT.wait(UIContextSWT.java:797)
    at test.test.testtest(test.java:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at com.windowtester.runtime.common.UITestCaseCommon.access$0(UITestCaseCommon.java:1)
    at com.windowtester.runtime.common.UITestCaseCommon$2.run(UITestCaseCommon.java:140)
    at com.windowtester.runtime.common.UITestCaseCommon$3.run(UITestCaseCommon.java:161)
    at com.windowtester.internal.runtime.junit.core.SequenceRunner$1.run(SequenceRunner.java:50)
Thread[main,5,main]:
    at org.eclipse.swt.SWT.error(SWT.java:4493)
    at org.eclipse.swt.SWT.error(SWT.java:4406)
    at org.eclipse.swt.SWT.error(SWT.java:4377)
    at org.eclipse.swt.widgets.Display.error(Display.java:1258)
    at org.eclipse.swt.widgets.Display.checkDevice(Display.java:764)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    at com.windowtester.runtime.swt.internal.junit.SWTExecutionMonitor.doWaitForFinish(SWTExecutionMonitor.java:161)
    at com.windowtester.internal.runtime.junit.core.AbstractExecutionMonitor.waitUntilFinished(AbstractExecutionMonitor.java:215)
    at com.windowtester.internal.runtime.junit.core.SequenceRunner.waitUntilFinished(SequenceRunner.java:79)
    at com.windowtester.internal.runtime.junit.core.SequenceRunner.exec(SequenceRunner.java:63)
    at com.windowtester.runtime.common.UITestCaseCommon.runUITest(UITestCaseCommon.java:157)
    at com.windowtester.runtime.common.UITestCaseCommon.runBare(UITestCaseCommon.java:138)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:252)
    at junit.framework.TestSuite.run(TestSuite.java:247)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Thread[Thread-0,5,main]:
    at com.windowtester.runtime.internal.factory.WTRuntimeManager.createReference(WTRuntimeManager.java:97)
    at com.windowtester.runtime.internal.factory.WTRuntimeManager.asReference(WTRuntimeManager.java:46)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.forWidget(SWTWidgetReference.java:325)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.asControlReferences(SWTWidgetReference.java:244)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference$1.call(CompositeReference.java:34)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference$1.call(CompositeReference.java:1)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.execute(SWTUIExecutor.java:142)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.run(SWTUIExecutor.java:97)
    at com.windowtester.runtime.swt.internal.widgets.DisplayReference.execute(DisplayReference.java:131)
    at com.windowtester.runtime.swt.internal.widgets.DisplayReference.execute(DisplayReference.java:110)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference.getChildControls(CompositeReference.java:32)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference.setChildren(CompositeReference.java:41)
    at com.windowtester.runtime.swt.internal.widgets.DecorationsReference.setChildren(DecorationsReference.java:74)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference$1.call(SWTWidgetReference.java:121)
    at com.windowtester.runtime.swt.internal.SWTUtils.safeExec(SWTUtils.java:68)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.getChildren(SWTWidgetReference.java:118)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.accept(SWTWidgetReference.java:306)
    at com.windowtester.runtime.swt.internal.widgets.finder.MatchCollector.findMatchesIn(MatchCollector.java:65)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.findWidgets(SWTWidgetReference.java:295)
    at com.windowtester.runtime.swt.internal.widgets.finder.SWTWidgetFinder$1.call(SWTWidgetFinder.java:122)
    at com.windowtester.runtime.swt.internal.widgets.finder.SWTWidgetFinder$1.call(SWTWidgetFinder.java:1)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.execute(SWTUIExecutor.java:142)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.access$0(SWTUIExecutor.java:140)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor$1.run(SWTUIExecutor.java:101)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
    at parisInit.ParisInit.stop(ParisInit.java:64)
    at parisInit.ParisInit.open(ParisInit.java:49)
    at parisWork.ParisWork.main(ParisWork.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.windowtester.internal.runtime.junit.core.launcher.LauncherFactory$MainRunner$1.run(LauncherFactory.java:131)
    at com.windowtester.internal.runtime.junit.core.launcher.LauncherFactory$SeparateThreadLauncher$1.run(LauncherFactory.java:100)
    at java.lang.Thread.run(Unknown Source)
Thread[Signal Dispatcher,9,system]:
Thread[Attach Listener,5,system]:
java.lang.ClassNotFoundException: com.windowtester.runtime.swt.internal.widgets.win32.win32.x86.WTRuntimeFactorySWT_win32_win32_x86
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at com.windowtester.runtime.internal.factory.WTRuntimeFactoryReferenceJava.createFactory(WTRuntimeFactoryReferenceJava.java:195)
    at com.windowtester.runtime.internal.factory.WTRuntimeFactoryReference.getFactory(WTRuntimeFactoryReference.java:80)
    at com.windowtester.runtime.internal.factory.WTRuntimeFactoryReference.createReference(WTRuntimeFactoryReference.java:67)
    at com.windowtester.runtime.internal.factory.WTRuntimeManager.createReference(WTRuntimeManager.java:97)
    at com.windowtester.runtime.internal.factory.WTRuntimeManager.asReference(WTRuntimeManager.java:46)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.forWidget(SWTWidgetReference.java:325)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.asControlReferences(SWTWidgetReference.java:244)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference$1.call(CompositeReference.java:34)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference$1.call(CompositeReference.java:1)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.execute(SWTUIExecutor.java:142)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.run(SWTUIExecutor.java:97)
    at com.windowtester.runtime.swt.internal.widgets.DisplayReference.execute(DisplayReference.java:131)
    at com.windowtester.runtime.swt.internal.widgets.DisplayReference.execute(DisplayReference.java:110)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference.getChildControls(CompositeReference.java:32)
    at com.windowtester.runtime.swt.internal.widgets.CompositeReference.setChildren(CompositeReference.java:41)
    at com.windowtester.runtime.swt.internal.widgets.DecorationsReference.setChildren(DecorationsReference.java:74)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference$1.call(SWTWidgetReference.java:121)
    at com.windowtester.runtime.swt.internal.SWTUtils.safeExec(SWTUtils.java:68)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.getChildren(SWTWidgetReference.java:118)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.accept(SWTWidgetReference.java:306)
    at com.windowtester.runtime.swt.internal.widgets.finder.MatchCollector.findMatchesIn(MatchCollector.java:65)
    at com.windowtester.runtime.swt.internal.widgets.SWTWidgetReference.findWidgets(SWTWidgetReference.java:295)
    at com.windowtester.runtime.swt.internal.widgets.finder.SWTWidgetFinder$1.call(SWTWidgetFinder.java:122)
    at com.windowtester.runtime.swt.internal.widgets.finder.SWTWidgetFinder$1.call(SWTWidgetFinder.java:1)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.execute(SWTUIExecutor.java:142)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor.access$0(SWTUIExecutor.java:140)
    at com.windowtester.runtime.swt.internal.widgets.SWTUIExecutor$1.run(SWTUIExecutor.java:101)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
    at parisInit.ParisInit.stop(ParisInit.java:64)
    at parisInit.ParisInit.open(ParisInit.java:49)
    at parisWork.ParisWork.main(ParisWork.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.windowtester.internal.runtime.junit.core.launcher.LauncherFactory$MainRunner$1.run(LauncherFactory.java:131)
    at com.windowtester.internal.runtime.junit.core.launcher.LauncherFactory$SeparateThreadLauncher$1.run(LauncherFactory.java:100)
    at java.lang.Thread.run(Unknown Source)
`

I'm not %100 sure what is going on, it seems to be failing in `com.windowtester.runtime.internal.factory.WTRuntimeManager.createReference` but I cant figure out why.  Any help would be appreciated.

**Comment by wendelkenEPA** [comment]
I determined that I did not have the proper jars in my build path. These were required in addition to the ones I already had:
wt-win32-win32-x86.jar
org.eclipse.ui.workbench

It seems to work with the exception of the `ui.ensureThat(myshell.isClosed());`.  If I include this I get a large stack trace of a bunch of threads failing and timing out.  If you have any idea's about that let me know and ill post the console output
